server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: account
  # 数据源配置
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/easybuy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 619314981
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid数据源配置
    druid:
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时时间
      max-wait: 60000
      #配置检测间隔时间，检测关闭空闲的连接
      time-between-eviction-runs-millis: 60000
      #配置一个连接最小的生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle:  true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache,指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截，去掉后监控界面SQL无法统计，‘wall’用于防火墙
      filters: stat,wall
      use-global-data-source-stat: true
      #打开mergeSQl功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
      #配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        #白名单IP
        #allow:
        #黑名单IP
        #deny:
      web-stat-filter:
        #过滤规则
        url-pattern: /*
        #忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gavin.entity

---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  profiles: prod
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.104:8761/eureka/
  instance:
    prefer-ip-address: true