server:
  port: 8081
spring:
  application:
    name: account
  datasource:
    name: easybuy
    url: jdbc:mysql://192.168.1.104:3306/easybuy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 619314981
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gavin.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
